eolo/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView, DetailView, UpdateView
from eolo.models import Station, Node, Sensor, Measure
from eolo.forms import StationForm, NodeForm, SensorForm, MeasureForm
from eolo.views import AddStationView, AddNodeView, AddSensorView, AddMeasureView
from tastypie.api import Api
from eolo.api import StationResource, NodeResource, SensorResource, MeasureResource

admin.autodiscover()
v1_api = Api(api_name='v1')
v1_api.register(StationResource())
v1_api.register(NodeResource())
v1_api.register(SensorResource())
v1_api.register(MeasureResource())


def get_obj_by_name(name):
    result_data = {
        'name': name,
        'paginate_by': 15,
        'detail_context_object_name': name,
        'list_context_object_name': "%ss" % name,
    }
    if name == 'station':
        result_data['model'] = Station
        result_data['queryset'] = Station.objects.all()
        result_data['add_view'] = AddStationView
        result_data['edit'] = StationForm
    elif name == 'node':
        result_data['model'] = Node
        result_data['queryset'] = Node.objects.all()
        result_data['add_view'] = AddNodeView
        result_data['edit'] = NodeForm
    elif name == 'sensor':
        result_data['model'] = Sensor
        result_data['queryset'] = Sensor.objects.all()
        result_data['add_view'] = AddSensorView
        result_data['edit'] = SensorForm
    elif name == 'measure':
        result_data['model'] = Measure
        result_data['queryset'] = Measure.objects.all()
        result_data['add_view'] = AddMeasureView
        result_data['edit'] = MeasureForm
    elif name == 'user':
        result_data['model'] = User
        result_data['queryset'] = User.objects.all()
        result_data['detail_context_object_name'] = 'usr'  # user and users already taken by login user
        result_data['list_context_object_name'] = 'usrs'  # user and users already taken by login user
        result_data['add_view'] = None
        result_data['edit'] = None
    return result_data

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logged_out.html'}, name='logout'),
    url(r'^$', 'eolo.views.home', name='home'),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # API
    url(r'^api/', include(v1_api.urls)),
)

for obj_name in ('station', 'node', 'sensor', 'measure', 'user'):
    add_view = get_obj_by_name(obj_name)['add_view']
    edit = get_obj_by_name(obj_name)['add_view']
    if add_view:
        urlpatterns += patterns('',
            # -> add
            url(r'^%s/add/$' % obj_name, login_required(add_view.as_view()), name="%s_add" % obj_name,),
        )

    if edit:
        urlpatterns += patterns('',
            url('^%s/edit/(?P<pk>[\w-]+)/$' % obj_name, login_required(UpdateView.as_view(
                            model=get_obj_by_name(obj_name)['model'],
                            form_class=get_obj_by_name(obj_name)['edit'],
                            template_name='eolo/%s/edit.html' % obj_name,
                            success_url='/%s/' % obj_name,
                        )), name="%s_edit" % obj_name,),
        )

    urlpatterns += patterns('',
        # -> detail
        url(r'^%s/(?P<pk>\d+)/$' % obj_name,
            login_required(DetailView.as_view(
                            context_object_name=get_obj_by_name(obj_name)['detail_context_object_name'],
                            model=get_obj_by_name(obj_name)['model'],
                            template_name='eolo/%s/detail.html' % obj_name,
                        )),
            name=obj_name
        ),
        # -> list
        url(r'^%s/$' % obj_name,
            login_required(ListView.as_view(
                            model=get_obj_by_name(obj_name)['model'],
                            paginate_by=get_obj_by_name(obj_name)['paginate_by'],
                            queryset=get_obj_by_name(obj_name)['queryset'],
                            context_object_name=get_obj_by_name(obj_name)['list_context_object_name'],
                            template_name='eolo/%s/list.html' % obj_name,
                        )),
            name="%s_list" % obj_name,
        ),
    )

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        url(r'^static/(?P<path>.*)$', 'serve', {'document_root': settings.STATIC_ROOT}),
        url(r'^media/(?P<path>.*)$',  'serve', {'document_root': settings.MEDIA_ROOT}),
    )

eolo/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Station(models.Model):
    name = models.CharField(max_length=20, default="")
    mantainer = models.ForeignKey(User, related_name='mantainer')

    class Meta:
        verbose_name = _('Station')
        verbose_name_plural = _('Stations')
        ordering = ['name', ]

    def __unicode__(self):
        return self.name


class Node(models.Model):
    name = models.CharField(max_length=20, default="")
    station = models.ForeignKey(Station, related_name='nodes')
    latitude = models.CharField(max_length=100, default="")
    longitude = models.CharField(max_length=100, default="")
    elevation = models.PositiveIntegerField(default=0)

    @property
    def coord(self):
        return "%s, %s" % (self.latitude, self.longitude)

    class Meta:
        verbose_name = _('Node')
        verbose_name_plural = _('Nodes')
        ordering = ['station', 'name', ]

    def __unicode__(self):
        return self.name


SENSOR_MEASURE_TYPE = (
    ('0', _('Thermometer')),
    ('1', _('Anemometer')),
    ('2', _('Barometer')),
    ('3', _('Hygrometer')),
    ('4', _('Pluviometer')),
)
SENSOR_SIGNAL_TYPE = (
    ('0', _('Analog')),
    ('1', _('Digital')),
)


class Sensor(models.Model):
    brand = models.CharField(max_length=80, default="", blank=True, null=True)
    model = models.CharField(max_length=80, default="", blank=True, null=True)
    node = models.ForeignKey(Node, related_name='sensors')
    measure_type = models.CharField(max_length=80, default="0", choices=SENSOR_MEASURE_TYPE)
    signal_type = models.CharField(max_length=80, default="0", choices=SENSOR_SIGNAL_TYPE)

    class Meta:
        verbose_name = _('Sensor')
        verbose_name_plural = _('Sensors')
        ordering = ['node', 'measure_type', 'signal_type', ]

    def __unicode__(self):
        return "[%s] %s - %s" % (self.node, self.get_measure_type_display(), self.get_signal_type_display())


MEASURE_UNIT_CHOICES = (
    ('0', _('percent')),
    ('1', _('celsius')),
    ('2', _('farenheit')),
    ('3', _('meter')),
    ('4', _('kilometer')),
    ('5', _('hPa')),
)


class Measure(models.Model):
    sensor = models.ForeignKey(Sensor, related_name='measures')
    timestamp = models.DateTimeField(auto_now=True)
    value = models.CharField(max_length=20, default="")
    unit = models.CharField(max_length=10, default="", choices=MEASURE_UNIT_CHOICES)

    class Meta:
        verbose_name = _('Measure')
        verbose_name_plural = _('Measures')
        ordering = ['timestamp', ]

    def __unicode__(self):
        return "%s: %s %s" % (self.sensor, self.value, self.get_unit_display())

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>Eolo - {% block head_title %} title {% endblock head_title %}</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/base.css">
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/skeleton.css">
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/layout.css">
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/styles.css">

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="{{ MEDIA_URL }}img/favicon.ico">
	<link rel="apple-touch-icon" href="{{ MEDIA_URL }}img/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="{{ MEDIA_URL }}img/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="{{ MEDIA_URL }}img/apple-touch-icon-114x114.png">
	<!-- JS
	================================================== -->
	<script src="{{ MEDIA_URL }}js/jquery-1.8.3.min.js"></script>
	<script src="{{ MEDIA_URL }}js/tabs.js"></script>

	{% block extra_head %}{% endblock extra_head %}

</head>
<body>
	{% include "includes/header.html" %}
	{% block main_content %}
		main content
	{% endblock main_content %}
	{% include "includes/footer.html" %}
<!-- End Document
================================================== -->
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% block head_title %} {% trans "Home" %} {% endblock head_title %}
{% block main_content %}

	<div class="container">
		<div class="row">
			<div class="sixteen columns">
				<h2>Bienvenido a EOLO<span id="logo_dot">.</span></h2>
			</div>
		</div>
		<div class="row">
			<div class="ten columns offset-by-four">
				<div class="icon_wrapper two columns alpha omega">
					<a class="icon" href="{% url station_list %}">
						<img src="{{ MEDIA_URL }}img/icons/station.png" alt="{% trans 'Stations' %}">
						{% trans "Stations" %}
					</a>
				</div>
				<div class="icon_wrapper two columns alpha omega">
					<a class="icon" href="{% url node_list %}">
						<img src="{{ MEDIA_URL }}img/icons/node.png" alt="{% trans 'Nodes' %}">
						{% trans "Nodes" %}
					</a>
				</div>
				<div class="icon_wrapper two columns alpha omega">
					<a class="icon" href="{% url sensor_list %}">
						<img src="{{ MEDIA_URL }}img/icons/sensor.png" alt="{% trans 'Sensor' %}">
						{% trans "Sensors" %}
					</a>
				</div>
				<div class="icon_wrapper two columns alpha omega">
					<a class="icon" href="{% url measure_list %}">
						<img src="{{ MEDIA_URL }}img/icons/measure.png" alt="{% trans 'Measures' %}">
						{% trans "Measures" %}
					</a>
				</div>
				<div class="icon_wrapper two columns alpha omega">
					<a class="icon" href="{% url user_list %}">
						<img src="{{ MEDIA_URL }}img/icons/user.png" alt="{% trans 'Users' %}">
						{% trans "Users" %}
					</a>
				</div>
				
		    </div>
		</div>
		<div class="row">
			&nbsp;
		</div>
	</div>
{% endblock main_content %}